default_settings:
      trainer_type: ppo
      hyperparameters:
        batch_size: 4
        buffer_size: 20
        learning_rate: 0.001
        beta: 5.0e-4
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
        beta_schedule: constant
        epsilon_schedule: linear
      network_settings:
        normalize: true
        hidden_units: 256
        num_layers: 3
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 1.0
      max_steps: 10000000
      time_horizon: 4
      summary_freq: 10000