default_settings:
      trainer_type: ppo
      hyperparameters:
        batch_size: 64
        buffer_size: 30000
        learning_rate: 1.0e-4
        beta: 5.0e-4
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
        beta_schedule: constant
        epsilon_schedule: linear
      network_settings:
        normalize: true
        hidden_units: 256
        num_layers: 3
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 2.0
        gail:
          strength: 0.01
          demo_path: PacManUnity/Assets/Demonstrations/BlinkyRecording_2.demo
      behavioral_cloning:
        strength: 0.1
        steps: 50000
        demo_path: PacManUnity/Assets/Demonstrations/BlinkyRecording_2.demo
      max_steps: 1000000
      time_horizon: 256
      summary_freq: 1000