behaviors:
    joe:
      trainer_type: ppo
      hyperparameters:
        batch_size: 10
        buffer_size: 100
        learning_rate: 3.0e-4
        beta: 5.0e-4
        epsilon: 0.4
        lambd: 0.99
        num_epoch: 3
        learning_rate_schedule: linear
        beta_schedule: constant
        epsilon_schedule: linear
      network_settings:
        normalize: false
        hidden_units: 128
        num_layers: 2
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 0.5
        gail:
          strength: 0.5
          demo_path: behaviorCloning/bc1.demo
      behavior_cloning:
        strength: 1
        demo_path: behaviorCloning/bc1.demo
      max_steps: 500000
      time_horizon: 64
      summary_freq: 10000